<a href="https://colab.research.google.com/github/LifeofAGeek/100-days-of-Applied-AI/blob/master/NeighbourhoodOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4.2 (Neighbourhood Operations)

1. Averaging
2. Max and
3. Min operation

Note: here take grid size from the user.

In [ ]:
import math
from random import *
import numpy as np

In [ ]:
def generateRandomImage(height, width):
    '''
        Description: Utility function to generate random matrix with grayscale values
    '''
    image = np.zeros([height, width], dtype=int) 
    for row in range(height):
        for col in range(width):
            image[row][col] = randint(0, 255)
    return image


In [ ]:
height = int(input("Image Height = "))
width = int(input("Image Width = "))
image = generateRandomImage(height, width)
print('Original Image: \n{}'.format(image))

Original Image: 
[[173 193 218 210]
 [167 122 194 255]
 [141  68 245 187]
 [157   8  14 226]]


In [ ]:
def generate_padded_matrix(matrix, gridSize):
    '''
        Description: Utility function to generate matrix with zero border padding
        Input: 
            paddedMatrix: an image pixel intensity matrix 
            gridSize: size of the grid
        Output: padded intensity matrix
    '''
    k = gridSize//2
    rows = len(matrix) + 2*k
    cols = len(matrix[0]) + 2*k
    paddedMatrix = np.zeros([rows, cols], dtype=int)
    
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            paddedMatrix[i+k][j+k] = matrix[i][j]
    return paddedMatrix  

### Grid Size Input and Padding

In [ ]:
gridSize = int(input("Grid Size = "))
paddedMatrix = generate_padded_matrix(image, gridSize)

### Neighbourhood Operation: Averaging

In [ ]:
def cellAverage(paddedMatrix: np.array, row: int, col: int, gridSize: int):
    '''
        Description: Utility function to calculate average intensity of a single pixel
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            row: cell row index
            col: cell column index
            gridSize: size of the grid
        Output: average intensity value of cell
    '''
    average = 0
    totalCellsInGrid = gridSize ** 2
    k = gridSize//2
    for i in range(row-k, row+k+1):
        for j in range(col-k, col+k+1):
            average = average + paddedMatrix[i][j]/totalCellsInGrid
    return math.floor(average)

In [ ]:
def averaging(paddedMatrix, gridSize, height, width):
    '''
        Description: Function to perform Averaging Spatial Operation on an image
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            i: cell row index
            j: cell column index
            gridSize: size of the grid
        Output: average intensity values
    '''
    print("Original Image with zero-padding: \n{}\n".format(paddedMatrix))
    result = np.zeros([len(paddedMatrix), len(paddedMatrix[0])], dtype=int)

    k = gridSize//2
    for i in range(height):
        for j in range(width):
            result[i+k][j+k] = cellAverage(paddedMatrix, i+k, j+k, gridSize)
    print("Image after Averaging: \n{}".format(result))
    return result  
            

In [ ]:
averageImage = averaging(paddedMatrix, gridSize, height, width)

Original Image with zero-padding: 
[[  0   0   0   0   0   0]
 [  0 173 193 218 210   0]
 [  0 167 122 194 255   0]
 [  0 141  68 245 187   0]
 [  0 157   8  14 226   0]
 [  0   0   0   0   0   0]]

Image after Averaging: 
[[  0   0   0   0   0   0]
 [  0  72 118 132  97   0]
 [  0  96 169 188 145   0]
 [  0  73 124 146 124   0]
 [  0  41  70  83  74   0]
 [  0   0   0   0   0   0]]


### Neighbourhood Operation: Min Grid

In [ ]:
def minCell(paddedMatrix: np.array, row: int, col: int, gridSize: int):
    '''
        Description: Utility function to calculate minimum intensity of a single pixel
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            row: cell row index
            col: cell column index
            gridSize: size of the grid
        Output: minimum intensity value of cell
    '''
    minVal = -1
    totalCellsInGrid = gridSize*gridSize
    k = gridSize//2
    for i in range(row-k, row+k+1):
        for j in range(col-k, col+k+1):
            if minVal == -1:
                minVal = paddedMatrix[i][j]
            else:
                minVal = min(minVal, paddedMatrix[i][j])
    return minVal

In [ ]:
def minGrid(paddedMatrix, gridSize, height, width):
    '''
        Description: Function to perform Minimum Spatial Operation on an image
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            i: cell row index
            j: cell column index
            gridSize: size of the grid
        Output: minimum intensity values
    '''

    print("Original Image with zero-padding: \n{}\n".format(paddedMatrix))
    result = np.zeros([len(paddedMatrix), len(paddedMatrix[0])], dtype=int)

    k = gridSize//2
    for i in range(height):
        for j in range(width):
            result[i+k][j+k] = minCell(paddedMatrix, i+k, j+k, gridSize)
    print("Image after Min Grid Operation: \n{}".format(result))
    return result  
            

In [ ]:
minImageGrid = minGrid(paddedMatrix, gridSize, height, width)

Original Image with zero-padding: 
[[  0   0   0   0   0   0]
 [  0 173 193 218 210   0]
 [  0 167 122 194 255   0]
 [  0 141  68 245 187   0]
 [  0 157   8  14 226   0]
 [  0   0   0   0   0   0]]

Image after Min Grid Operation: 
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0 68 68  0  0]
 [ 0  0  8  8  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


### Neighbourhood Operation: Max Grid

In [ ]:
def maxCell(paddedMatrix, row, col, gridSize):
    '''
        Description: Utility function to calculate maximum intensity of a single pixel
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            row: cell row index
            col: cell column index
            gridSize: size of the grid
        Output: maximum intensity value of cell
    '''
    maxVal = -1
    totalCellsInGrid = gridSize ** 2
    k = gridSize//2
    for i in range(row-k, row+k+1):
        for j in range(col-k, col+k+1):
            if maxVal == -1:
                maxVal = paddedMatrix[i][j]
            elif paddedMatrix[i][j] > maxVal:
                maxVal = paddedMatrix[i][j]
    return maxVal

In [ ]:
def maximum(paddedMatrix, gridSize, height, width):
    '''
        Description: Function to perform Maximum Spatial Operation on an image
        Input: 
            paddedMatrix: an image pixel intensity matrix with zero padded border values
            i: cell row index
            j: cell column index
            gridSize: size of the grid
        Output: maximum intensity values
    '''
    print("Original Image with zero-padding: \n{}\n".format(paddedMatrix))
    result = np.zeros([len(paddedMatrix), len(paddedMatrix[0])], dtype=int)
    k = gridSize//2

    for i in range(height):
        for j in range(width):
            result[i+k][j+k] = maxCell(paddedMatrix, i+k, j+k, gridSize)
    print("Image after Maximum Neighborhood Operation: \n{}".format(result))
    return result  
            

In [ ]:
maxImage = maximum(paddedMatrix, gridSize, height, width)

Original Image with zero-padding: 
[[  0   0   0   0   0   0]
 [  0 173 193 218 210   0]
 [  0 167 122 194 255   0]
 [  0 141  68 245 187   0]
 [  0 157   8  14 226   0]
 [  0   0   0   0   0   0]]

Image after Maximum Neighborhood Operation: 
[[  0   0   0   0   0   0]
 [  0 193 218 255 255   0]
 [  0 193 245 255 255   0]
 [  0 167 245 255 255   0]
 [  0 157 245 245 245   0]
 [  0   0   0   0   0   0]]
