<a href="https://colab.research.google.com/github/LifeofAGeek/100-days-of-Applied-AI/blob/master/Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4
#### 1. Normalization of intensity values between \[0 to K\]

In [ ]:
import math
from random import *
import numpy as np

In [ ]:
def getMaxIntensityValue(matrix):
    '''
        Description: Function to get the maximum intensity pixel value of an image
        Input: a 2-D matrix containing image pixel intensity values
        Output: maximum intensity value
    '''
    maximumIntensity = 0
    m = len(matrix)
    n = len(matrix[0])

    for i in range(m):
        for j in range(n):
            if matrix[i][j] > maximumIntensity:
                maximumIntensity = matrix[i][j]
    return maximumIntensity

In [ ]:
def normalization(matrix, K):
    '''
        Description: Function to normalize intensity values of an image
        Input: a 2-D intensity matrix
        Output: a 2-D intensity matrix with normalized intensity values in the range [0 to K]
    '''
    m = len(matrix)
    n = len(matrix[0])
    maxIntensityValue = getMaxIntensityValue(matrix)
    normalizedMatrix = np.zeros([m,n], dtype=float)
    
    for i in range(m):
        for j in range(n):
            normalizedMatrix[i][j] = (matrix[i][j]/maxIntensityValue) * K
    
    return normalizedMatrix

In [ ]:
def generateRandomImage(height, width):
    '''
        Description: Utility function to generate random matrix with grayscale values
    '''
    image = np.zeros([image_width, image_height], dtype=int) 
    for row in range(height):
        for col in range(width):
            image[row][col] = randint(0, 1000)
    return image


### User Input

In [ ]:
print("Enter Image Size\n")
image_height = int(input("Image Height"))
image_width = int(input("Image Width"))
print('Image Height: {}\nImage Width: {}'.format(image_height, image_width))

Enter Image Size

Image Height: 4
Image Width: 4


In [ ]:
image = generateRandomImage(image_height, image_width)

In [ ]:
print("Generated Image: \n{}".format(image))

Generated Image: 
[[888 331 148 104]
 [885 334 869 492]
 [280 311 562  46]
 [134  80 452 926]]


### Apply normalization on input image

In [ ]:
# apply normalization
K = int(input("Enter K for normalization: "))
normalizedImage = normalization(image, K)

### Final Result after Normalization

In [ ]:
print("Original Image:\n\n{}\n\n".format(image))
print("Normalized Image for K = {}\n\n {}".format(K, normalizedImage))

Original Image:

[[888 331 148 104]
 [885 334 869 492]
 [280 311 562  46]
 [134  80 452 926]]


Normalized Image for K = 255

 [[244.53563715  91.15010799  40.75593952  28.63930886]
 [243.70950324  91.9762419  239.30345572 135.48596112]
 [ 77.10583153  85.6425486  154.76241901  12.66738661]
 [ 36.90064795  22.03023758 124.47084233 255.        ]]
